package de.dnpm.dip.integration.support

import java.nio.charset.StandardCharsets.UTF_8
import java.nio.file.{Files, Paths}
import java.security.{KeyFactory, PrivateKey}
import java.security.interfaces.RSAPublicKey
import java.security.spec.{MGF1ParameterSpec, X509EncodedKeySpec}
import java.util.Base64
import javax.crypto.{Cipher, EncryptedPrivateKeyInfo, SecretKeyFactory}
import javax.crypto.spec.{IvParameterSpec, OAEPParameterSpec, PBEKeySpec, PSource, SecretKeySpec}
import org.bson.Document
import play.api.libs.json.{JsValue, Json}

/** Decryption of zKDK backups, i.e. the counterpart of central-data-node's RsaHybridEncryptionServiceImpl.
 *
 *  Uses the keypair from the README: crypto/private.pem (passphrase in crypto/private_passphrase.txt),
 *  whose public half is deployed as config/ccdn-{mtb,rd}/public.pem.
 */
object BackupCrypto {

  /** Value of EncryptionService.Encrypted.algorithm */
  val Algorithm = "RSA-OAEP-SHA256+AES-256-CBC"

  /** OAEP parameters as documented in RsaHybridEncryptionServiceImpl (openssl: rsa_oaep_md:sha256, rsa_mgf1_md:sha256).
   *  Spelled out, because the JCE default of "OAEPWithSHA-256AndMGF1Padding" is MGF1 with SHA-1.
   */
  val OaepParams = new OAEPParameterSpec("SHA-256", "MGF1", MGF1ParameterSpec.SHA256, PSource.PSpecified.DEFAULT)

  val EncryptedFields = Set("algorithm", "encryptedKey", "iv", "ciphertext")

  private def pemBytes(path: String): Array[Byte] =
    Base64.getDecoder.decode(
      Files.readString(Paths.get(path))
        .replaceAll("-----[A-Z ]+-----", "")
        .replaceAll("\\s", "")
    )

  lazy val deployedPublicKey: RSAPublicKey =
    KeyFactory.getInstance("RSA")
      .generatePublic(new X509EncodedKeySpec(pemBytes("config/ccdn-mtb/public.pem")))
      .asInstanceOf[RSAPublicKey]

  /** Length in bytes of an RSA-encrypted block under [[deployedPublicKey]] */
  def rsaBlockBytes: Int = (deployedPublicKey.getModulus.bitLength + 7) / 8

  /** Expects an encrypted PKCS#8 key ("BEGIN ENCRYPTED PRIVATE KEY"), as generated by the README's openssl command. */
  lazy val privateKey: PrivateKey = {
    // Like openssl's -passin file:, only the first line is the passphrase
    val passphrase = Files.readString(Paths.get("crypto/private_passphrase.txt")).linesIterator.next()
    val encrypted  = new EncryptedPrivateKeyInfo(pemBytes("crypto/private.pem"))
    // The parameters name the concrete scheme (e.g. PBEWithHmacSHA256AndAES_256);
    // getAlgName may only yield "PBES2", depending on the JDK
    val scheme = encrypted.getAlgParameters.toString
    val cipher = Cipher.getInstance(scheme)
    cipher.init(
      Cipher.DECRYPT_MODE,
      SecretKeyFactory.getInstance(scheme).generateSecret(new PBEKeySpec(passphrase.toCharArray)),
      encrypted.getAlgParameters
    )
    KeyFactory.getInstance("RSA").generatePrivate(encrypted.getKeySpec(cipher))
  }

  /** Decrypt the "content" sub-document of a backup document into the original JSON payload,
   *  joining the ciphertext from its parts if it was split (see [[CcdnMongo.ciphertext]]).
   */
  def decrypt(content: Document): JsValue = {
    def bytes(field: String) = Base64.getDecoder.decode(content.getString(field))

    val rsa = Cipher.getInstance("RSA/ECB/OAEPPadding")
    rsa.init(Cipher.DECRYPT_MODE, privateKey, OaepParams)
    val aesKey = rsa.doFinal(bytes("encryptedKey"))

    val aes = Cipher.getInstance("AES/CBC/PKCS5Padding")
    aes.init(Cipher.DECRYPT_MODE, new SecretKeySpec(aesKey, "AES"), new IvParameterSpec(bytes("iv")))
    Json.parse(new String(aes.doFinal(Base64.getDecoder.decode(CcdnMongo.ciphertext(content))), UTF_8))
  }
}
